apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
  - name: gitops_repository_prefix
    value: julien
  - name: gitops_repository
    value: ssh://git@github.com/J-kolaric/spring-petclinic-deploy.git
  - name: gitops_branch
    value: dev
  - name: gitops_user_name
    value: my_commit_user
  - name: gitops_user_email
    value: my_commit_user@vmware.com
  - name: gitops_commit_message
    value: "Delivery for my environment"
  - name: gitops_ssh_secret
    value: julien-ssh-secret 
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/J-kolaric/spring-petclinic.git
      ref:
        branch: main
